### ISSUE TITLE
How we can use this library 

### ISSUE THREAD

**Issue by MR-Mostafa** [mammad2c/mmd-persian-datepicker#2]
Hi,
Thank you for publish this libery, but I think there is some problems:
1) How we can use this library in our projects? please write a document and explain how we can use it. 
2) How we can build all js your code in single files without dependencies such as momentjs or moment-jalali.
3) Which browsers supported?

**Comment by mammad2c** [comment]
hi
this library still in development.
i will create the documents after version 1
